### ISSUE TITLE
I cancelled my milestone but the funds have not yet returned to donor

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapp#2061] opened 2021-04-24 16:00 UTC
I cancelled this milestone: https://beta.giveth.io/milestone/support-for-the-caretaker-of-diamante-luz
because the funds were distributed to the landlord in local currency.

![image](https://user-images.githubusercontent.com/74267818/115964869-b1a76080-a4e3-11eb-952e-297653b4b99d.png)

@Danibelle was the donor of the funds but she has not yet received the funds back.
How long does the process take? Does it need to go to the bridge?

Thanks for your help to monitor this

**Comment by MoeNick** [comment] 2021-04-24 16:14
@mohammadranjbarz can u pls take a look?

**Comment by mohammadranjbarz** [comment] 2021-04-24 16:35
> @mohammadranjbarz can u pls take a look?
@MoeNick 
I don't know what should happen in this scenario,  I don't think if feathers do the job or not (Unfortunetely I don't know much about bridge)

Maybe Amin can help

**Comment by MoeNick** [comment] 2021-04-24 19:44
> > @mohammadranjbarz can u pls take a look?
> > @MoeNick
> > I don't know what should happen in this scenario,  I don't think if feathers do the job or not (Unfortunetely I don't know much about bridge)
> 
> Maybe Amin can help

@aminlatifi I know you're off these days, but appreciate if you can take a look if you have time.

**Comment by Danibelle** [comment] 2021-04-26 15:24
![image](https://user-images.githubusercontent.com/39466970/116108439-c103e680-a668-11eb-808a-afa879819d66.png)

**Comment by aminlatifi** [comment] 2021-04-27 08:46
@mohammadranjbarz This donation is canceled successfully, but money is not reverted
```
{"_id":{"$oid":"5ffcc3da0563d75cf55d9f7a"},"status":"Canceled","mined":true,"parentDonations":["5ffcc2380563d75cf55d9f75"],"isReturn":false,"lessThanCutoff":false,"usdValue":333,"amount":"333000000000000000000","amountRemaining":"333000000000000000000","giverAddress":"0x5D28FE1e9F895464aab52287d85Ebff32B351674","ownerId":{"$numberLong":"2287"},"ownerTypeId":"5fbbcd41188f980d941470e6","ownerType":"milestone","pledgeId":"8521","commitTime":{"$date":"2021-01-11T21:30:37.000Z"},"createdAt":{"$date":"2021-01-11T21:30:37.000Z"},"txHash":"0x7d4fd3ed1fcb5a5cf2ab273d88d129a8249ff3bd06cc987271407b9498ea673e","comment":"Travis, Sarah Luz, and baby Ariz are dedicated to this land, the people of this place, and bring valuable contributions to the community through permaculture education and action, cultural relations and exchange, and leadership in both indigenous practices as well as sociocratic governance.  They are a shining example of family living in harmony with nature, embodying a regenerative and respectful lifestyle.","actionTakerAddress":"0x5D28FE1e9F895464aab52287d85Ebff32B351674","homeTxHash":"0xb30148fdc1698a6582adf03253c9ced0329f468055a53d32756122da5cc64aee","tokenAddress":"0x6b175474e89094c44da98b954eedeac495271d0f","updatedAt":{"$date":"2021-04-24T15:49:00.951Z"},"__v":0}
```

To money return back to the owner the pledge (here 8521) should be normalized. We have a process in feathers to normalize canceled donations, but it has not worked as expected. Please investigate it. Please see `getPledgesToNormalize` function in `src/blockchain/normalizer.js` of feathers.

**Comment by mohammadranjbarz** [comment] 2021-04-27 12:22
@Danibelle 
Did your problem solved?
It was a problem with normalizing pledge, I think your money should be back already

**Comment by aminlatifi** [comment] 2021-04-28 11:11
@mohammadranjbarz Feathers hadn't normalized the pledge, please investigate the issue.

**Comment by mohammadranjbarz** [comment] 2021-04-28 11:13
> @mohammadranjbarz Feathers hadn't normalized the pledge, please investigate the root cause.

Sure, I'll do it

**Comment by mohammadranjbarz** [comment] 2021-04-30 09:00
After some investigating I knew that we had no error  in normalizing pledges since 26 days ago

<img width="1440" alt="Screen Shot 1400-02-10 at 12 48 15" src="https://user-images.githubusercontent.com/9850545/116671156-da34cc00-a9b5-11eb-9878-1bc79f5ea9bf.png">

That the cause of them was mongo connection, anyway with logs of 3 days ago ( before restarting server  and solving the problem), So with exisitng logs we cant know much more about now, ( I read the codes it seems ok, I tested it multiple times , it was ok) 
So the only thing I could do was adding some informative logs for normalizing pledges, so next time if this happened we will know better whats happened ( also I hope new queue solve problems like this)
@aminlatifi 
If you are agreeing with me we can close this issue for now ( I think the Dani's money is back to his account)

**Comment by aminlatifi** [comment] 2021-05-03 12:33
Thanks @mohammadranjbarz 
Let's keep it in Bug & Ops pipe to find the cause later.

**Comment by mohammadranjbarz** [comment] 2021-05-03 12:34
> Thanks @mohammadranjbarz 
> Let's keep it in Bug & Ops pipe to find the cause later.

I agree👍

**Closed** 2024-06-24 22:23 UTC
Labels: bug, can't reproduce, hotfix
