### ISSUE TITLE
Did the bridge fail to relay a tx to mainnet?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1790] opened 2021-02-11 12:24 UTC
<img width="913" alt="Screen Shot 2021-02-11 at 7 13 08 AM" src="https://user-images.githubusercontent.com/14945613/107635962-43852880-6c6c-11eb-9d07-c70576f353e2.png">

475 tx payment request missing? 

It is for: https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/601ab700f9e6e877930e9690

it was never sent: https://etherscan.io/address/0x7dFA9dc2d05F9bA15d1265E9AE5A79928efa57f9#tokentxns

- [x] Confirm its not in the bridge queue already
- [x] Investigate why this happened
- [x] understand and document why this happened
- [x] make a new tx to pay the man!

**Comment by aminlatifi** [comment] 2021-02-12 12:40
It was bridge, I made bridge to reprocess events again. It's data is fixed now and this payment transactions are shown correctly.

**Comment by aminlatifi** [comment] 2021-02-12 12:42
I believe the root cause is web3 provider connection is down sometimes and events happening at the moment are missed.

**Comment by aminlatifi** [comment] 2021-02-12 12:49
Or maybe db size has grown and it's now working correctly. By the way I couldn't find any clue in logs, nothing was reported at the time tx happend.

**Comment by GriffGreen** [comment] 2021-02-13 13:54
thank you @aminlatifi are there any issues that need to be made as a result of this?

**Comment by aminlatifi** [comment] 2021-02-13 15:59
> thank you @aminlatifi are there any issues that need to be made as a result of this?

As there isn't any real clue, the rewriting bridge monitor to adapt new DB and new event processing design would be the issue

**Comment by aminlatifi** [comment] 2021-02-13 16:05
Created giveth/giveth-bridge-monitor#44

**Closed** 2021-02-22 16:33 UTC
