### ISSUE TITLE
Create a donation address option (Feature request)

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#446] opened 2018-07-25 22:50 UTC
Can i put a bounty on part or all of this?

Tension:
You can't donate to anything by simply sending to an address.

Proposal:

I would like for there to be a button that would allow any DAC, campaign, or milestone to create an anon donation address.

I have a proposed  smart contract design:

Create a factory that deploys a contract for every project when this button is pushed

That contract is a very simple contract with 
1. Payable fallback function to receive money
2. `sendAnonDonation()` function that anyone can push. The Giver is 0x0 (does that have a GiverID :-D?)
3. escapeHatch and all that escape hatch destination being the giveth multisig, escape hatch caller, the owner of the `project`(Delegate, milestone manager, campaign manager)

We should track this feature in the dapp and maintain a list of these deployed contracts and probably even canceling a campaign or milestone require the reviewer to call the `sendAnonDonation()`

---questions----

It would be nice if it is a donation to a DAC that we could skip the 3 day waiting period.

The hard part of course is making the UX/UI inside of the dapp. that i have no advice for.

**Comment by vojtechsimetka** [comment] 2018-07-26 13:07
We are actually discussing feature request strategy as a financing model for the DApp. As for the idea I think we can talk about it, maybe there is an easy and cheap solution.

**Comment by perissology** [comment] 2018-08-09 20:17
relevant comment: https://github.com/Giveth/giveth-dapp/issues/145#issuecomment-401913852

**Comment by vojtechsimetka** [comment] 2018-10-05 17:49
Duplicate of #478

**Closed by vojtechsimetka** 2018-10-05 17:49 UTC
Labels: feature request
