### ISSUE TITLE
Issue in BETA when deleting Milestone Proof

### ISSUE THREAD

**Issue by MorganGR** [Giveth/giveth-dapp#690] opened 2019-02-27 14:28 UTC
In the current BETA version when trying to delete a Milestone Proof the button is enabled (big X) and clickable but when clicking and Saving (Updating) the Milestone Proof the line is not removed.
![milestoneproofenabledx](https://user-images.githubusercontent.com/34093087/53497398-f79b4200-3a9b-11e9-9ea2-654015a6c32c.PNG)
![milestoneproofremoved](https://user-images.githubusercontent.com/34093087/53497399-f833d880-3a9b-11e9-85e4-499de0447e51.PNG)

**Comment by ewingrj** [comment] 2019-02-27 17:56
has this milestone already been created?

**Comment by MorganGR** [comment] 2019-02-27 18:14
Yes!

**Comment by ewingrj** [comment] 2019-02-27 18:51
okay, so the bug here is that the "X" is visible. Once a milestone is created, you should not be able to remove a "proof" b/c the proofs are used to calculate the maxAmount of the milestone.

thanks for reporting

**Comment by GriffGreen** [comment] 2019-04-08 16:49
Simple UI fix just remove the x from being displayed

**Comment by MorganGR** [comment] 2019-05-06 08:53
@mroberts10 do you know if anyone will look at this? (minor UI fix)

**Comment by mroberts10** [comment] 2019-05-20 17:31
I will be taking a look at this one now. @MorganGR

**Comment by mroberts10** [comment] 2019-06-10 17:20
Amin to take a look at this.

**Comment by aminlatifi** [comment] 2019-06-11 11:55
OK.

**Comment by GriffGreen** [comment] 2019-06-24 17:29
Might be fixed when andre was working on drafts... to be checked

**Comment by arbreton** [comment] 2019-06-27 00:18
Fixed in 859

**Comment by aminlatifi** [comment] 2019-06-27 11:22
I checked out master branch, and test again. The bug still exists.
I recorded a video to show that.
[simplescreenrecorder-2019-06-27_15.48.51.zip](https://github.com/Giveth/giveth-dapp/files/3334357/simplescreenrecorder-2019-06-27_15.48.51.zip)

**Comment by arbreton** [comment] 2019-06-27 14:40
I couldn’t reproduce the error anymore, the problem was that when you deleted proof when editing it didn’t get deleted, now it deletes fine

**Comment by arbreton** [comment] 2019-06-27 14:45
If it still needs the “X” to be removed when it has been already created that should be an easy modification 

Assigned to Amin

**Closed** 2019-07-02 06:19 UTC
Labels: bug
