### ISSUE TITLE
30k Dai Missing from Commons Stack Campaign

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1005] opened 2019-09-27 14:07 UTC
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e

probably related to #996 When i do the math on milestones filled... It seems like we are missing about 30k Dai worth of donations...

**Comment by arbreton** [comment] 2019-10-01 22:39
@GriffGreen funds were reverted !, working on a longterm fix!

**Comment by arbreton** [comment] 2019-10-02 21:48
@GriffGreen , @ewingrj , need to check on the smart contract if a donations has balance left, is there a way to do that? just a way to verify if a pledge has been used before to completely ensure that the funds are available to use

**Comment by ewingrj** [comment] 2019-10-03 19:47
yes, you can call `lp.pledges(id)` or something like that

**Comment by arbreton** [comment] 2019-10-06 02:14
Trying to interact with the contract directly @ewingrj but the function getPledge is not returning any values i think maybe the input id is wrong or something.

Trying on this LP contract, is this where the pledges should be stored?
https://rinkeby.etherscan.io/address/0x2f3c81fa2b0e171a135c128142dbf877213c5071#readContract

**Comment by ewingrj** [comment] 2019-10-07 13:45
nope, you can't use etherscan. Need to use something that allows you to enter the abi & contract address directly. https://www.mycrypto.com/contracts/interact

That's the base contract, which controls the logic, but not where the data is stored. That is all stored in the proxy contract. You need to call that method on the proxy contract. The address you need is found in the config file of the giveth-dapp

**Comment by arbreton** [comment] 2019-10-08 04:46
@ewingrj Tried with my crypto before, i tried it again today, this is the proxy contract that i'm using https://rinkeby.etherscan.io/address/0x8eb047585abed935a73ba4b9525213f126a0c979

What i did is used the ABI from this contract https://rinkeby.etherscan.io/address/0x2f3c81fa2b0e171a135c128142dbf877213c5071, on the proxy using my crypto, trying to getPledge, but is returning nothing

Is there something else we might be missing?

**Comment by ewingrj** [comment] 2019-10-08 19:49
works for me w/ the pledgeId you have in a screenshot above. did you change the network to rinkeby? mycrypto defaults to mainnet

**Comment by arbreton** [comment] 2019-10-09 00:28
That was it!, thank you alot @ewingrj i identified the pledges mismatching on the mongoDB from the contract, updated accordingly all the funds on the common stack should be updated now @GriffGreen, is there any milestones that got conflicted during this period that may invalid donations?

**Comment by arbreton** [comment] 2019-10-10 05:10
So i updated the records on the donations but the Syncing process seems to be turning back the donations!, i think the donations are wrongfully assigned to this milestone https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d8be3baad3696263686d152, this is where the problem started, it had 90+ repeated donations, so the same donations 90 times, and that subtracted the funs on the campaign

Is there a way to unassign this funds and re-assign them back to the campaign @ewingrj ?

**Comment by arbreton** [comment] 2019-10-11 23:13
This are the 2 pledges that still have money in it and when updated on Mongo they get reverted to 0 for some reason

**4587
5491** 

was looking at the owner and it's 1402 which is correct, it's very strange

**Comment by aminlatifi** [comment] 2019-10-25 18:59
After dealing with the issue, reading code to find the cause and modifying DB to cope here are my achievements.
We have tried to  sync DB with blockchain pledges and after each try, donations are drained from db records! I did tried syncing again and filled donation on DB. I found where donations are going:
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d5a5795420f06212039fdb5
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d55cfe0ded7183fafb04956
![image](https://user-images.githubusercontent.com/5684607/67595538-c4689a00-f773-11e9-8403-ffaac183d619.png)
![image](https://user-images.githubusercontent.com/5684607/67595568-d34f4c80-f773-11e9-9b54-90ae10184701.png)
I uploaded images because I want to delete the committed donations created by this issue.

We have a good new and a bad news!
Good news is campaign donations are not drained any more and remainingAmount of a donation belongs to campaign in DB has no changed after my last modification
The bad news is we are not sure about the cause. I have studied feather and Dapp code of related part on some extent. I think we have received multiple `transfer` events that should be one.  My clue was that updateTime of corresponding `transfer` event in DB is updated each time a campaign donation is drained. @ewingrj I like to know your idea about it.

**Comment by aminlatifi** [comment] 2019-10-25 19:19
This issue was a good excuse to talk about one of important shortage of feather. We don't have enough logging of events occurred and request reaching to feather. This prevents us from debugging issues occurring in real deployment.

**Comment by aminlatifi** [comment] 2019-10-25 20:56
In order to prevent such issues, maybe we should prevent processing of transmit events which are duplicate. It seems tuple of txHash and parent fields is enough to detect duplicate transmit.

**Comment by aminlatifi** [comment] 2019-10-25 20:58
@arbreton Me and you should resync donation records in database with amounts in pledge.

**Comment by arbreton** [comment] 2019-10-29 20:58
Resyncing but still donations get reset everytime they are delegated again for some reason, i think a temporal fix could be resyncing every time donations get delegated

**Comment by aminlatifi** [comment] 2019-10-29 22:56
@arbreton did it happen again? I have no access to dapp right now.
If yes, let's debug immediately. I am ready to start. Maybe we should implement feather internal events right now.

**Comment by aminlatifi** [comment] 2019-10-30 08:58
I started to add transactional changes feature to feather by this issue: https://github.com/Giveth/feathers-giveth/issues/134
@arbreton I don't have permission on https://github.com/Giveth/feathers-giveth please assign me to this issue.

**Comment by aminlatifi** [comment] 2019-11-01 11:28
> Resyncing but still donations get reset everytime they are delegated again for some reason, i think a temporal fix could be resyncing every time donations get delegated

They went here https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d829497ad3696263686cc6d
![image](https://user-images.githubusercontent.com/5684607/68021906-eacc8f00-fcb7-11e9-9d19-7b1674c67594.png)

**Comment by arbreton** [comment] 2019-11-01 21:44
Exactly!, i think we need to find the record that is responsible for instructing the delegating this funds to here

**Comment by aminlatifi** [comment] 2019-11-04 04:47
> Exactly!, i think we need to find the record that is responsible for instructing the delegating this funds to here

I believe they are some `Transmit` type event records which are processing multiple time. Two examples are these two:
```
{
    "_id" : ObjectId("5d5c50a8459b4a695b0dbc96"),
    "topics" : [],
    "status" : "Processed",
    "address" : "0x8eB047585ABeD935a73ba4b9525213F126A0c979",
    "blockNumber" : 4946735,
    "transactionHash" : "0xd8753fe1a6217e1b7040c571f26a5becbfb7ba41fadb337c4eb241e0c61dd8c4",
    "transactionIndex" : 3,
    "blockHash" : "0x77c40e93e14156ee433cc7db3ab4e049807333545815aa6a8be4c84c01e10c15",
    "logIndex" : 5,
    "id" : "log_3fb88c56",
    "returnValues" : {
        "0" : "4587",
        "1" : "5447",
        "2" : "5000000000000000000000",
        "from" : "4587",
        "to" : "5447",
        "amount" : "5000000000000000000000"
    },
    "event" : "Transfer",
    "signature" : "0xaf6151f5085accf2d57e1e7bf7601d3b3982e0de7e9a90f032f8554de9c104f6",
    "raw" : {
        "data" : "0x00000000000000000000000000000000000000000000010f0cf064dd59200000",
        "topics" : [ 
            "0xaf6151f5085accf2d57e1e7bf7601d3b3982e0de7e9a90f032f8554de9c104f6", 
            "0x00000000000000000000000000000000000000000000000000000000000011eb", 
            "0x0000000000000000000000000000000000000000000000000000000000001547"
        ]
    },
    "confirmations" : 6,
    "createdAt" : ISODate("2019-08-20T19:57:28.876Z"),
    "updatedAt" : ISODate("2019-11-04T04:32:35.853Z"),
    "__v" : 0
}
```
And
```
{
    "_id" : ObjectId("5d5c50b7459b4a695b0dbca5"),
    "topics" : [],
    "status" : "Processed",
    "address" : "0x8eB047585ABeD935a73ba4b9525213F126A0c979",
    "blockNumber" : 4946736,
    "transactionHash" : "0x208750eb2f5cb1ab264f4401317daed8fbcbbfb0506949db9f03e4aa101ac676",
    "transactionIndex" : 6,
    "blockHash" : "0xa7a83b19977d1a9fac38bdffedec877bbadcd6846af051b92fadff57d0417d94",
    "logIndex" : 6,
    "id" : "log_3bbef20a",
    "returnValues" : {
        "0" : "4587",
        "1" : "5449",
        "2" : "240000000000000000000",
        "from" : "4587",
        "to" : "5449",
        "amount" : "240000000000000000000"
    },
    "event" : "Transfer",
    "signature" : "0xaf6151f5085accf2d57e1e7bf7601d3b3982e0de7e9a90f032f8554de9c104f6",
    "raw" : {
        "data" : "0x00000000000000000000000000000000000000000000000d02ab486cedc00000",
        "topics" : [ 
            "0xaf6151f5085accf2d57e1e7bf7601d3b3982e0de7e9a90f032f8554de9c104f6", 
            "0x00000000000000000000000000000000000000000000000000000000000011eb", 
            "0x0000000000000000000000000000000000000000000000000000000000001549"
        ]
    },
    "confirmations" : 6,
    "createdAt" : ISODate("2019-08-20T19:57:43.604Z"),
    "updatedAt" : ISODate("2019-11-04T04:32:36.191Z"),
    "__v" : 0
}
```
Notice updatedAt timestamps are so close while the have been created much earlier. Currently, they are still reprocessing, see this: https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d55cfe0ded7183fafb04956

**Comment by aminlatifi** [comment] 2019-11-04 04:51
We have updated web3 module (which was so dated) and modified feathers to prevent processing `Transmit` events if they produce repetitive records. I hope they resolve issue after they are deployed.

**Comment by arbreton** [comment] 2019-11-04 04:59
Yes looks like the same issue, we should update records in here aswell, not sure if this issue was reported, perfect!, will test and review PR hopefully we can erradicate this problem

**Comment by GriffGreen** [comment] 2019-11-04 17:30
ok i delegated some!

**Comment by aminlatifi** [comment] 2019-11-09 09:35
@arbreton Have you deployed the feather version with double transmit processing prevention on beta server? If yes, please let me know to resync donations of the campaign.

**Comment by GriffGreen** [comment] 2019-12-02 17:45
we have to do this one more time

**Comment by aminlatifi** [comment] 2020-02-20 07:17
The footprints are cleaned by this https://github.com/Giveth/feathers-giveth/issues/146#issuecomment-588651227

**Comment by aminlatifi** [comment] 2020-02-20 07:17
@arbreton @GriffGreen I guess we can close this

**Closed** 2020-02-25 21:30 UTC
Labels: bug
