### ISSUE TITLE
Refactor Donation Flow to have Infinite approve

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#735] opened 2019-03-29 13:35 UTC
Ok to aggregate a few comments from: 
https://docs.google.com/document/d/1gmtcmUaowGux8AIFjRRYDM8uT4kYZoymr0KJjk4Ed_w/edit?usp=sharing
and other experiences since this issue was made... i have a few suggestions:

Unlock Donations: The "Let's Try" pop up can be removed if we make a better flow for approve and donate... We should offer the infinite approve option and the approve just this amount option on the donation pop up page and strengthen our approve backend flow:

<img width="877" alt="Screen Shot 2020-04-19 at 3 50 59 PM" src="https://user-images.githubusercontent.com/14945613/79689644-7b8f2b00-8256-11ea-9cfa-61946edcceb9.png">

I like how 1inch does it... https://1inch.exchange/#/DAI/ETH:

<img width="890" alt="Screen Shot 2020-04-19 at 3 48 47 PM" src="https://user-images.githubusercontent.com/14945613/79689473-5a7a0a80-8255-11ea-9bef-9bc6f8658d8f.png">

And if the person already has unlimited approve then there is just a donate and a Lock button.

<img width="923" alt="Screen Shot 2020-04-19 at 5 46 49 PM" src="https://user-images.githubusercontent.com/14945613/79692512-d0866d80-8265-11ea-9661-788d515d2221.png">

This might need some more design thought on the buttons...? Maybe we can just copy 1inch's flow, but combine the Unlock and Donate buttons. I asked them why they dont do this and they said they will look into it!
This is the most important piece... It hopefully would turn what is now, at fastest, a 4 click donation with a 2 min time span into as short as a 2 click donation in less than 10 second time span ;-D
...

**Comment by GriffGreen** [comment] 2019-03-29 17:37
this is for 5 days of review and then we need to make separate issues

**Comment by GriffGreen** [comment] 2019-04-08 16:39
#580  is looped into this

**Comment by mroberts10** [comment] 2019-04-08 16:40
Estimate 2 days fulltime work.

**Comment by GriffGreen** [comment] 2019-05-22 10:57
As a donor I want to create a message when i donate and see it on the Campaign page

**Comment by markoprljic** [comment] 2019-05-27 13:10
> https://docs.google.com/document/d/1gmtcmUaowGux8AIFjRRYDM8uT4kYZoymr0KJjk4Ed_w/edit?usp=sharing
> 
> I make several suggestions in this document... which is an example doc for onboarding 404 to the dapp.

I was just checking the Donation flow and I couldn't reproduce this step from your google doc: "Another pop up will come up, click “Let’s Try” and then you will have to confirm 2 txs, one tx to approve the 290 DAI withdraw and one tx to execute the withdraw."

Does that mean that this has been fixed?

I just noticed missing the text field for the message.

**Comment by GriffGreen** [comment] 2020-04-27 17:12
Instadapp triggers 2 transactions at the same time

**Comment by GriffGreen** [comment] 2020-05-04 16:37
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5ea22bcb1db39e3252bd1743

Bridge doesnt show the donation on mainnet?
but shows it on rinkeby??? https://rinkeby.etherscan.io/tx/0x937de0ee2eadf9522745aaa9b44ebf72e6c81213cb3997b2c4da22a5a98aa9c5

<img width="1434" alt="Screen Shot 2020-05-04 at 6 36 38 PM" src="https://user-images.githubusercontent.com/14945613/80990229-4e39a400-8e36-11ea-9e4b-58233254d5c0.png">

**Comment by GriffGreen** [comment] 2020-05-04 16:47
https://beta.giveth.io/campaigns/5e908206cb08e33938daffb4

**Comment by GriffGreen** [comment] 2020-05-11 16:48
On Develop

**Comment by aminlatifi** [comment] 2020-08-13 19:48
@GriffGreen I guess we should close this.

**Closed** 2020-10-29 15:02 UTC
Labels: feature request
