### ISSUE TITLE
Ropsten wallet balance isnt showing up on Develop.giveth.io

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#350] opened 2018-05-14 18:25 UTC
Although I can succesfully donate to campaigns with the Ropsten ETH in my wallet, I can't see the balance... maybe the wallet page is reverencing the balance on main net?

<img width="484" alt="screen shot 2018-05-14 at 9 21 23 am" src="https://user-images.githubusercontent.com/14945613/40015899-940c5fb4-5769-11e8-9013-6ed445e1411a.png">
<img width="987" alt="screen shot 2018-05-14 at 9 21 51 am" src="https://user-images.githubusercontent.com/14945613/40015901-9428f8a4-5769-11e8-8180-2790b82d6deb.png">

**Comment by vojtechsimetka** [comment] 2018-05-14 18:36
You need to cancel the donation and then you will see the Ropsten ETH balance. It is actually a token representing Ropsten ETH that is in your wallet. IMHO not a bug but very unclear and should be reviewed.

**Comment by vojtechsimetka** [comment] 2018-05-20 09:35
I take this issue as there will have to be more changes for the wallet.

**Comment by perissology** [comment] 2018-05-24 13:49
fixed in 7d40290f3ab94b5f809064b050132d3d57517403

**Closed by perissology** 2018-05-24 13:49 UTC
