### ISSUE TITLE
"Oh no! You are not whitelisted" error

### ISSUE THREAD

**Issue by Jeff-Emmett** [Giveth/giveth-dapp#970] opened 2019-08-29 01:38 UTC
Trying to edit my milestone:  https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d486d5be2b294308843fd4f

And getting an error when clicking the edit button.  Hoping to add in my final receipts and finalize this milestone!

**Comment by arbreton** [comment] 2019-08-29 03:59
Let me take a look Jeff!

**Comment by arbreton** [comment] 2019-08-29 04:28
Can you please try again @Jeff-Emmett ?

**Comment by Jeff-Emmett** [comment] 2019-08-29 13:39
Still getting the same error:

Error message:

Minified React error #185; visit
https://reactjs.org/docs/error-decoder.html?invariant=185 for the full
message or use the non-minified dev environment for full errors and
additional helpful warnings.

**Comment by arbreton** [comment] 2019-08-29 22:09
There seems to be another issue, this is a recent problem just happened today, for some reason is not happening in develop is just happening on beta.giveth.io !, im investigating further this situation , will report asap

**Comment by arbreton** [comment] 2019-08-29 23:23
I confirmed now on beta.giveth.io is fixed now, please keep me posted @Jeff-Emmett

**Closed by arbreton** 2019-08-29 23:23 UTC
Labels: bug
