### ISSUE TITLE
CryptoXmas Milestone status hanging in 'My Milestones'

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#686] opened 2019-02-22 16:47 UTC
Looks like there's a bug in completing this [milestone](https://beta.giveth.io/campaigns/5c0e84ea06392d786b64d484/milestones/5c0e959806392d786b64d48c), I am the reviewer:

![image](https://user-images.githubusercontent.com/39466970/53257162-76a50a80-3697-11e9-896f-43d99e031742.png)

**Comment by ewingrj** [comment] 2019-02-28 00:20
this was caused by https://github.com/Giveth/feathers-giveth/issues/105.

this milestone should be fixed now, but not the main issue

**Closed by ewingrj** 2019-02-28 00:20 UTC
Labels: bug
