### ISSUE TITLE
Decimals need to be consistent within the DApp

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#315] opened 2018-04-21 17:04 UTC
These decimals are getting cut off in the front end on the milestones but not on the back end, which causes a discrepancy when triple checking proposed payments. The test ether still uses 2 more decimals than are shown in the milestone - can we have the back end cut down to the 8th point just like the front end?
@deamme @twmilli you guys might be able to help?
<img width="337" alt="screen shot 2018-04-21 at 6 57 37 pm" src="https://user-images.githubusercontent.com/38163206/39086692-1a8c3342-4596-11e8-9d3c-ff48834e3d69.png">

**Comment by vojtechsimetka** [comment] 2018-04-21 17:44
No. We do not want to modify smart contracts and all the logic to cut these. Why can't we just ignore anything after 8 digits in triple check?

**Comment by lorelei1** [comment] 2018-04-22 15:55
@deamme that sounds great, cut off the decimals right from the source.

**Comment by vojtechsimetka** [comment] 2018-04-22 16:35
@deamme no need to modify it in feathers or anywhere like that. Instead the tool taking it out https://github.com/Quazia/multi-send-cli should cut off the undesired decimals. IMHO not a DApp issue.

**Comment by deamme** [comment] 2018-04-26 19:51
@vojtechsimetka I guess, whatever generates the excel should be fixed.

**Comment by GriffGreen** [comment] 2018-05-28 05:12
This IMO is an aesthetics issue as well as a usability issue... This screen shot is from the Develop dapp
<img width="676" alt="screen shot 2018-05-27 at 10 02 46 pm" src="https://user-images.githubusercontent.com/14945613/40598030-27424d62-61fa-11e8-9b51-0afd7d769a23.png">

This is important and should be something that is fixed int the dapp all the way thru the DApp... 

It causes problems to everyone working with the dapp (it has take sooooo many hours from the governance circle i cant even start)  

Eventually some people will want to export CSVs and such to play with their data and they will be hosed if there is inconsistencies and on top of that, it is aesthetically displeasing to have these long string of numbers and inconsistencies :-(

**Comment by GriffGreen** [comment] 2018-05-30 18:50
<img width="691" alt="screen shot 2018-05-29 at 11 02 17 am" src="https://user-images.githubusercontent.com/14945613/40741092-60b83e38-63ff-11e8-955d-bcd1f725820c.png">
Another instance of this inconsistency... Kay thought that there was a lot of decimals in his payout because thats what he saw when he was making the milestone, but what he actually gets paid is something else.

Luckily i was able to edit the milestone (thank you!) to keep the transparency and accuracy high!

**Comment by vojtechsimetka** [comment] 2018-05-30 19:29
No he is actually paid all the decimals, it is just being displayed to users with 8 decimal places. We agreed to do that in past, deam actually implemented it in the DApp. We decided to do so because any digit trimming introduces errors and especially in expenses it could be hard to reproduce same values on frontend and backend.

**Comment by GriffGreen** [comment] 2018-06-15 15:53
he isnt paid that amount tho.... the amount he is paid is recorded on the blockchain as having 10 decimal points... see in this weeks pay out: 
https://etherscan.io/tx/0x2ee94812b755d11198ae1e506b1981c08d1a0b77ef6c17d42f07548bee09c90d

the inconsistency is a (negligible) transparency issue but what is not negligible is that it causes users to create milestones with inconsistencies in the numbers...

See this week: 

<img width="619" alt="screen shot 2018-06-15 at 8 42 36 am" src="https://user-images.githubusercontent.com/14945613/41477357-da0ad4f0-7078-11e8-841e-71303ee3e20f.png">

The amount displayed on the front end needs to be consistent in the various places

**Comment by perissology** [comment] 2018-06-15 16:00
are you guys regenerating the tx data used to send the payments (b/c you need to remove duplicates, etc)?

**Comment by GriffGreen** [comment] 2018-06-15 16:01
usu yeah... its pretty rare that the first data works each time.

**Comment by GriffGreen** [comment] 2018-06-15 16:05
but the real thing is we make this test send and we trim decimals off because we can't audit effectively otherwise... IMO other users will have similar issues... Just cause Ethereum is silly (using big numbers that almost no software can easily deal) doesnt mean we have to be silly. 

It is in no way a priority right now, i just have to keep dealing with this bug that is labeled "won't fix" so i can't help but make frustrated comments ;-)

**Closed** 2018-10-04 21:48 UTC
Labels: still discussing..., wontfix
