### ISSUE TITLE
Can't give people easy way to donate to a milestone

### ISSUE THREAD

**Issue by ljg583** [Giveth/giveth-dapp#516] opened 2018-11-05 12:34 UTC
Is there any way to have a milestone generate an address to make donations easier and more accessible??

I created a milestone for the Berlin AirBnB and shared the link to the milestone to the people that stayed so they can send donations.  At different times that link wouldn't load for people or they didn't have the right wallet extension.  This process would be very seamless if I could just send an address for people to donate.

**Comment by vojtechsimetka** [comment] 2018-11-26 10:02
As @FrederikBolding said, duplicate of #478 :) Closing

**Closed by vojtechsimetka** 2018-11-26 10:02 UTC
