### ISSUE TITLE
add links to etherscan (rinkeby and mainnet) in the wallet page

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#349] opened 2018-05-14 16:20 UTC
it always nice to be able to see the status of my deposit, and the other account activity from the wallet page

**Comment by vojtechsimetka** [comment] 2018-05-14 16:38
@GriffGreen is this a duplicate of #98 ?

**Comment by vojtechsimetka** [comment] 2018-08-20 10:36
This was fixed in 30b81813748da09df6b3b1cb6427976af2906af5

**Closed by vojtechsimetka** 2018-08-20 10:36 UTC
