### ISSUE TITLE
When you donate too much the UI doesn't reflect the smart contracts

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#514] opened 2018-10-31 08:01 UTC
<img width="684" alt="screen shot 2018-10-31 at 8 57 50 am" src="https://user-images.githubusercontent.com/14945613/47773766-6aadcb00-dceb-11e8-8273-9af9ca603a1f.png">
This is not the truth... I think this is related to other issues in the past

https://beta.giveth.io/campaigns/5b3d94ba329bc64ae74d1421/milestones/5bbcf4e2089683199bce55cb

**Comment by vojtechsimetka** [comment] 2018-11-21 08:49
The milestone now shows correct amount and I am unable to reproduce locally, closing for now.

**Closed by vojtechsimetka** 2018-11-21 08:49 UTC
