### ISSUE TITLE
Is your wallet unlocked? Appears after each action on develop.

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#367] opened 2018-05-29 07:48 UTC
**Description:**
About 10 seconds after taking any action the Oh no! message appears saying "Something went wrong with the transaction. Is your wallet unlocked?". However, the transaction has been broadcasted correctly about 10 seconds prior to the error message and it always finishes without any problem.

**The corresponding error when reporting:**

>       Description of the Error:
>       Something went wrong with the transaction. Is your wallet unlocked?
> 
>       Transaction link:
>       https://rinkeby.etherscan.io/tx/0xc51087c449af16c1df31bfb52be248cd596982050a367e87390ac18d8c9ec3cb => {}

**Comment by perissology** [comment] 2018-05-29 13:27
did https://github.com/Giveth/giveth-dapp/commit/c287675c0b4600d6a323f90d746f8af8d695b790 not fix it?

**Comment by vojtechsimetka** [comment] 2018-05-29 13:40
No, just tried after clearing cache and in private window.

Here is a video: https://www.dropbox.com/s/uruuj1pq526dpry/%23367.mov?dl=0

**Comment by perissology** [comment] 2018-05-29 13:58
I think the problem is I'm ignoring "unknown transaction" errors, but we're also getting a log of "Failed to check for transaction receipt" errors that need to be ignored as well

**Comment by perissology** [comment] 2018-06-13 16:10
fixed by updating geth node

**Closed by perissology** 2018-06-13 16:10 UTC
