### ISSUE TITLE
Can't update my profile

### ISSUE THREAD

**Issue by vincentlg** [Giveth/giveth-dapp#123] opened 2017-10-27 07:55 UTC
<img width="1179" alt="capture d ecran 2017-10-27 a 09 47 31" src="https://user-images.githubusercontent.com/813911/32093525-d8d61bb2-bafc-11e7-9ee7-2678bee22e99.png">

**Comment by vincentlg** [comment] 2017-10-27 10:21
For info, I tried to fix it, but I do not reproduce it on my local environment ... 
![local-test](https://user-images.githubusercontent.com/813911/32099626-46693312-bb11-11e7-9e7f-cbfa9bb51db0.png)

**Comment by vsimetka** [comment] 2017-10-27 15:32
Hi @vincentlg it is not clear to me under what conditions this problem happens, I tried myself but I can't reproduce. If you want we could schedule a meeting where you will show it to me? Contact me on the Giveth slack at `@vojtech`.

**Comment by vincentlg** [comment] 2017-10-27 15:52
Hi @vsimetka sorry my description was not very clear. this bug was triggered on mvp.giveth.io (first screenshot) I tried to reproduce it locally (second screenshot) but I failed to reproduce it. Now I can not reproduce either on mvp.giveth.io ... so I propose to close this ticket for now, I would create a new one if I have more elements

**Comment by perissology** [comment] 2017-10-27 15:58
So I'm not sure what the cause of this is, but I have ran into it before. I suspect `web3`, or `web3-provider-engine` as it has happened both via testrpc and mvp (parity ropsten node).

If you immediately try again, it will successfully send the tx.

@vincentlg was this the first time saving your profile, or an update?

**Comment by vincentlg** [comment] 2017-10-27 16:08
it happened at the first update of my profile

**Comment by vsimetka** [comment] 2017-10-27 16:12
Might be related to #77

**Comment by perissology** [comment] 2017-10-27 17:18
I don't think so. I'm pretty sure I knew the cause of #77 and it should be fixed in the feathers develop branch. I still need to verify though.

Anyways, I can take a look at this after devcon

**Comment by satyavh** [comment] 2017-11-10 10:04
I cannot reproduce this

**Comment by vsimetka** [comment] 2017-11-27 16:50
Did not encounter any more issues, should be fixed if not create new issue.

**Closed by vsimetka** 2017-11-27 16:50 UTC
Labels: bug
