### ISSUE TITLE
Milestones skipping place

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#393] opened 2018-06-18 22:14 UTC
Minor 'issue', but often Milestones 'move' place, suddenly old Milestones end up in second place, Milestone that should be there disappears.

I see this movement often, goes away on refresh.
Seems to always happen for sure when creating a new Milestone.

Most recent example, before refresh: 
Creating New Milestone, old Milestone from January pops up on the right. See screenshot below.

![image](https://user-images.githubusercontent.com/6533925/41565121-9c5d02b0-7355-11e8-81ea-3b563c526475.png)

After refresh: 

![image](https://user-images.githubusercontent.com/6533925/41565168-d97c07ae-7355-11e8-80e2-dcb783672dc5.png)

Other example before & after refresh

![image](https://user-images.githubusercontent.com/6533925/41603082-8921221c-73dc-11e8-942f-d03050ac4396.png)
https://alpha.giveth.io/campaigns/R1WkS0obautijkvJ

![image](https://user-images.githubusercontent.com/6533925/41603125-a12f048c-73dc-11e8-8b36-053430004e19.png)

**Comment by vojtechsimetka** [comment] 2018-07-20 16:33
I think this has been fixed with migration to Mongo. I could not reproduce, please reopen if not.

**Closed by vojtechsimetka** 2018-07-20 16:33 UTC

**Comment by krrisis** [comment] 2018-08-07 14:31
seems ok, thx!
