### ISSUE TITLE
Allowed to collect a milestone that has already been Paid Out

### ISSUE THREAD

**Issue by Jeff-Emmett** [Giveth/giveth-dapp#1430] opened 2020-08-19 20:38 UTC
Hello there,

I'm getting a warning "Oh no! Nothing to withdraw. There are no donations to this Milestone." from the below milestone that has been filled successfully.

https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5ed075da6e542114b5a58897

Thanks!
Jeff

**Comment by aminlatifi** [comment] 2020-08-20 16:37
@Jeff-Emmett Thanks for reporting. This error happens eventually and we haven't found the root cause yet! 
However your tx has gone through and your money is paid :D

**Comment by GriffGreen** [comment] 2020-08-20 16:39
![Screen Shot 2020-08-20 at 6 36 00 PM](https://user-images.githubusercontent.com/14945613/90799952-3e29cf80-e314-11ea-818c-bfba134c1e65.png)

Thank you for making this issue! The payment was made on August 5th... not sure why it wasn't marked as paid and gave you the option to withdraw. 

Here is the tx:
https://etherscan.io/tx/0xa134a4d6104e5bcf73a9475866bfc9007d34853b6ee2d85fb6ec61fc9ea69ff6

**Comment by GriffGreen** [comment] 2020-08-27 16:31
Similar to other errors...

**Comment by GriffGreen** [comment] 2020-08-27 16:32
Need to find the root cause... need more investigation

**Comment by GriffGreen** [comment] 2020-08-27 16:32
The real issue is that you have the ability to collect the funds when you shouldnt

**Comment by aminlatifi** [comment] 2020-08-31 08:19
> Hello there,
> 
> I'm getting a warning "Oh no! Nothing to withdraw. There are no donations to this Milestone." from the below milestone that has been filled successfully.
> 
> https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5ed075da6e542114b5a58897
> 
> Thanks!
> Jeff

Just a point, did you press collect/disburse button two times?

**Comment by aminlatifi** [comment] 2020-08-31 08:21
It's done. It has been setup to call method on xDAI network on every donation to develop.giveth.io
The result will be events shown here: https://blockscout.com/poa/xdai/address/0x5b293019C338D9D902f20A924E49Dd41819D7D63/transactions

**Closed** 2020-08-31 08:21 UTC
