### ISSUE TITLE
Can't propose new milestones

### ISSUE THREAD

**Issue by ljg583** [Giveth/giveth-dapp#248] opened 2018-02-28 12:11 UTC
![screen shot 2018-02-28 at 1 07 47 pm](https://user-images.githubusercontent.com/35914957/36786934-8487cbf8-1c88-11e8-89ef-0d7521484d7f.png)

In attempt to propose new milestones in the Governance Campaign, I am receiving the above "X Oh No!" message
I don't see any missing information that would prevent the milestone from being proposed....

**Comment by c1e0** [comment] 2018-02-28 13:24
I tried to propose a new milestone in the Communication Campaign. I received an "Oh no!" alert. 

<img width="872" alt="screen shot 2018-02-28 at 14 17 45" src="https://user-images.githubusercontent.com/35862890/36789780-0153dab4-1c93-11e8-9539-291081400c53.png">

**Comment by vojtechsimetka** [comment] 2018-03-22 03:29
@ljg583 @c1e0 is this still a problem? I can't reproduce.

**Comment by c1e0** [comment] 2018-03-22 03:50
Sorry @vojtechsimetka, I should have closed this issue. It was due to not having a verified address.

**Closed** 2018-03-22 03:51 UTC
